name: UpstateSU-GRU COVID-19 Forecast
description: By the SUNY Upstate Medical University and Syracuse University COVID-19 Prediction Team
show_downloads: false
theme: jekyll-theme-slate
defaults:
  -
    scope:
      paths: ""
    values:
      layout: "default"
